// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppForTests.Shared.Models.DbModels
{
    public partial class TestsHistory
    {
        public TestsHistory()
        {
            QuestionsHistories = new HashSet<QuestionsHistory>();
        }

        public int Id { get; set; }
        public DateTime Date { get; set; }
        public int UserId { get; set; }
        public int TestId { get; set; }
        public int TimeSpentInSeconds { get; set; }

        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<QuestionsHistory> QuestionsHistories { get; set; }
    }
}