// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppForTests.Shared.Models.DbModels
{
    public partial class User
    {
        public User()
        {
            TestsHistories = new HashSet<TestsHistory>();
        }

        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public bool IsAdmin { get; set; }

        public virtual ICollection<TestsHistory> TestsHistories { get; set; }
    }
}